theme: jekyll-theme-slate<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QNN9HY6KJD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QNN9HY6KJD');
</script>
google_analytics: UA-210890054-1
plugins:
  - jekyll-sitemap
